### ISSUE TITLE
Project relicense

### ISSUE THREAD

**Issue by loudblow** [nosix/PyMineHub#5]
Can you relicense PyMineHub code under a permissive license? I used some parts of your code to implement RakNet library in python and want to publish it under a permissive license like the original implementation, because it's a comprehensive and widely used library.

**Comment by nosix** [comment]
Is Apache 2.0 license ok?

**Comment by nosix** [comment]
I'm sorry. I was considering changing the license, but since the project I am referencing is licensed under LGPL, I will license it under LGPL as well.

**Comment by loudblow** [comment]
> I'm sorry. I was considering changing the license, but since the project I am referencing is licensed under LGPL, I will license it under LGPL as well.

I was checked PMMP and PMH code in the details and here is no any kind of reused parts of code from PMMP

**Comment by nosix** [comment]
How was it checked?

PMMP was created in a different programming language, so I don't think there is any part of the code that is being reused as is. However, since PMH's code was created based on the structure and ideas of PMMP's code, I consider it to be a derivative work.

**Comment by loudblow** [comment]
I compared the PMMP and PMH sources at the time of the last active commit (March 2, 2018). Moreover, since you used PMMP as a reference but did not include or modify its code directly (this also applies to code directly translated from one language to another), you shouldn't license it under the same license.

**Comment by nosix** [comment]
I am not an expert on licensing, but the GNU FAQ states the following about translating to a different programming language:

https://www.gnu.org/licenses/gpl-faq.en.html#TranslateCode

> If the original program is licensed under certain versions of the GNU GPL, the translated program must be covered by the same versions of the GNU GPL.

**Comment by loudblow** [comment]
I mean what you used LGPL-licensed code just as a reference for your own code, and your code is a separate and independent work that is not a derivative or modification of the LGPL-licensed code, so you may choose any license. I can compare this situation with song-writing and music industry at all: if you used someone else's song as a reference - it's your own song, but if you used some parts of the song - it's a copyright issue and you should have an agreement of a copyright holder to use the part in your own song.
